services:
  # Frontend service
  frontend:
    build:
      context: ../..
      dockerfile: deploy/dev/frontend.Dockerfile
    container_name: slcw-frontend-dev
    ports:
      - "127.0.0.1:8092:9002"  # Map to dev frontend port as per nginx config
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-}
    networks:
      - slcw-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ping service (test microservice)
  ping-service:
    build:
      context: ../../services/ping-service
      dockerfile: Dockerfile
    container_name: slcw-ping-service-dev
    ports:
      - "127.0.0.1:9001:8080"
    networks:
      - slcw-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  slcw-dev:
    name: slcw-dev
    driver: bridge