-- Migration DOWN: 003_populate_classifiers.down.sql
--
-- Ранее этот скрипт удалял дистрибутивные записи классификаторов,
-- добавленные `003_populate_classifiers.up.sql`.
-- Начиная с перехода на YAML-источник (`game-data/classifiers`) и
-- утилиту `scripts/item_loader`, откатывать данные через SQL больше не требуется.
--
-- Скрипт оставлен пустым для сохранения истории миграций.