openapi: 3.1.0
info:
  title: Shard Legends Public API (Dev)
  description: |
    Агрегированная спецификация публичных эндпоинтов сервисов **Auth** и **Inventory** для окружения *dev*.
    Содержит только методы, доступные фронтенду через API Gateway.
  version: 1.0.0

servers:
  - url: https://dev-dim.slcw.dimlight.online/
    description: Dev API Gateway (домашняя страница mini-app)
  - url: https://dev.slcw.dimlight.online/
    description: Dev API Gateway (основной домен)

paths:
  /auth:
    $ref: "../specs/auth-service-openapi.yml#/paths/~1auth"
  /inventory:
    $ref: "../specs/inventory-service-openapi.yml#/paths/~1inventory"
  /items/details:
    $ref: "../specs/inventory-service-openapi.yml#/paths/~1items~1details"
