global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Ping Service  
  - job_name: 'ping-service'
    static_configs:
      - targets: ['slcw-ping-service-dev:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Telegram Bot Service
  - job_name: 'telegram-bot-service'
    static_configs:
      - targets: ['telegram-bot-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # API Gateway (nginx metrics if enabled)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL exporter (optional)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis exporter (optional)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']