openapi: 3.0.3
info:
  title: Deck Game Service API
  description: |
    Публичные эндпоинты мини-игры «Дека» для выдачи ежедневных сундуков.
  version: 1.0.0
  contact:
    name: Shard Legends Team

servers:
  - url: http://localhost:9000/api/
    description: Local Dev (direct)

security:
  - bearerAuth: []

tags:
  - name: Public
    description: Публичные методы для фронтенда

paths:
  /deck/daily-chest/status:
    get:
      tags: [Public]
      summary: Получить ожидаемый комбо и статус сундуков
      operationId: getDailyChestStatus
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /deck/daily-chest/claim:
    post:
      tags: [Public]
      summary: Получить награду за выполненное комбо
      operationId: claimDailyChest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimRequest'
      responses:
        '200':
          description: Награда получена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimResponse'
        '400':
          description: Ошибка бизнес-валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Рецепт не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/InternalError'

  /deck/chest/open:
    post:
      tags: [Public]
      summary: Открыть сундуки указанного типа и качества
      operationId: openChest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenChestRequest'
      responses:
        '200':
          description: Сундуки успешно открыты
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenChestResponse'
        '400':
          description: Ошибка бизнес-валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Рецепт или сундук не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/deck-game/buy-item:
    post:
      summary: Покупка предмета по рецепту или коду товара
      description: |
        Позволяет купить предмет по идентификатору рецепта или по коду товара (с указанием качества и серии).
        Если найден ровно один подходящий рецепт — используется его id. Если не найден или найдено несколько — возвращается ошибка.
      tags:
        - DeckGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipe_id:
                  type: string
                  format: uuid
                  description: Идентификатор рецепта
                item_code:
                  type: string
                  description: Код покупаемого предмета
                quality_level_code:
                  type: string
                  description: Качество (например, small/medium/large/base)
                collection_code:
                  type: string
                  description: Серия/коллекция (если применимо)
                quantity:
                  type: integer
                  default: 1
                  minimum: 1
      responses:
        '200':
          description: Успешная покупка
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        code:
                          type: string
                        quality:
                          type: string
                        collection:
                          type: string
                        quantity:
                          type: integer
        '400':
          description: Ошибка запроса
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '404':
          description: Рецепт не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '409':
          description: Найдено несколько подходящих рецептов
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '500':
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Пользовательский JWT c RS256-подписью Auth Service

  schemas:
    StatusResponse:
      type: object
      required: [expected_combo, finished, crafts_done]
      properties:
        expected_combo:
          type: integer
          minimum: 5
          maximum: 15
        finished:
          type: boolean
        crafts_done:
          type: integer
          minimum: 0
          maximum: 10
        last_reward_at:
          type: string
          format: date-time
          nullable: true

    ClaimRequest:
      type: object
      required: [combo, chest_indices]
      properties:
        combo:
          type: integer
          minimum: 5
          maximum: 15
        chest_indices:
          type: array
          minItems: 1
          maxItems: 6
          items:
            type: integer
            minimum: 1
            maximum: 6

    ItemInfo:
      type: object
      required: [item_id, item_class, item_type, name, description, image_url, collection, quality_level, quantity]
      properties:
        item_id:
          type: string
          format: uuid
        item_class:
          type: string
        item_type:
          type: string
        name:
          type: string
        description:
          type: string
        image_url:
          type: string
        collection:
          type: string
          nullable: true
        quality_level:
          type: string
        quantity:
          type: integer
          minimum: 1

    ClaimResponse:
      type: object
      required: [items, next_expected_combo, crafts_done]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemInfo'
        next_expected_combo:
          type: integer
        crafts_done:
          type: integer

    OpenChestRequest:
      type: object
      description: Ровно одно из полей `quantity` или `open_all` должно быть задано.
      required: [chest_type, quality_level]
      properties:
        chest_type:
          type: string
          description: Тип сундука
          enum: [resource_chest, reagent_chest, booster_chest, blueprint_chest]
        quality_level:
          type: string
          enum: [small, medium, large]
        quantity:
          type: integer
          minimum: 1
          maximum: 100
        open_all:
          type: boolean
          description: Если true, открыть все доступные сундуки указанного типа и качества
      oneOf:
        - required: [quantity]
        - required: [open_all]
      example:
        chest_type: resource_chest
        quality_level: medium
        open_all: true

    OpenChestResponse:
      type: object
      required: [items, quantity_opened]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemInfo'
        quantity_opened:
          type: integer

    ErrorResponse:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
        message:
          type: string

  responses:
    Unauthorized:
      description: Отсутствует или недействительный JWT
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: missing_token
            message: Missing Authorization header

    InternalError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: internal_error
            message: Unexpected server error 